website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_user, login_required, logout_user, current_user
from .models import User, Organization
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from website.forms import SignUpForm, LoginForm

auth = Blueprint("auth", __name__)


@auth.route('/', methods=["GET", "POST"])
@auth.route('/login', methods=["GET", "POST"])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            if check_password_hash(user.password, form.password.data):
                login_user(user, remember=True)
                flash(f"Successfully logged in as {user.email}", category="success")
                return redirect(url_for("views.dashboard"))
            else:
                flash("Incorrect password.", category="danger")
        else:
            flash("User with that email does not exist.", category="danger")

    return render_template("login.html", form=form)


@auth.route('logout')
def logout():
    logout_user()
    flash("Logged out successfully.", category="info")
    return redirect(url_for("auth.login"))


@auth.route('/sign-up', methods=["GET", "POST"])
def sign_up():
    form = SignUpForm()

    if form.validate_on_submit():
        organization = Organization.query.filter_by(name=form.organization.data).first()
        if not organization:
            organization = Organization(name=form.organization.data)
            db.session.add(organization)

        new_user = User(email=form.email.data,
                        first_name=form.first_name.data,
                        last_name=form.last_name.data,
                        role=form.role.data,
                        password=generate_password_hash(form.password1.data, method="sha256"))
        organization.team.append(new_user)
        db.session.add(new_user)
        db.session.commit()

        login_user(new_user, remember=True)
        flash(f"Account created successfully! You are now logged in as {new_user.email}", category="success")

        return redirect(url_for("views.dashboard"))

    if form.errors != {}:
        for err_msg in form.errors.values():
            flash(f"{err_msg}", category="danger")

    return render_template("sign_up.html", form=form)


@auth.route('/demo')
def demo():
    # Login as demo user if selected from login/sign-up page.
    demo_user = User.query.filter_by(email="demo@email.com").first()
    login_user(demo_user, remember=True)
    flash(f"Successfully logged in as {demo_user.email}", category="success")
    return redirect(url_for("views.dashboard"))

website/views.py
import flask_login
from flask import Blueprint, render_template, request, flash, redirect, url_for, session
from flask_login import login_required, current_user
from website.forms import CreateNewProjectForm, init_CreateNewTicketForm, EditProfileForm, NewCommentForm
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from .models import User, Organization, Project, Ticket, Comment, TicketEdit


views = Blueprint("views", __name__)


@views.route('/dashboard')
@login_required
def dashboard():

    user = User.query.get(current_user.id)
    organization = Organization.query.get(user.organization_id)
    low = []
    medium = []
    high = []
    urgent = []

    for project in organization.projects:
        for ticket in project.tickets:
            if ticket.priority == "Low":
                low.append(ticket)
            elif ticket.priority == "Medium":
                medium.append(ticket)
            elif ticket.priority == "High":
                high.append(ticket)
            elif ticket.priority == "Urgent":
                urgent.append(ticket)
    priority_data = [len(low), len(medium), len(high), len(urgent)]

    return render_template("dashboard.html", priority_data=priority_data)


# Create routes
@views.route('/my-projects/create-project', methods=["GET", "POST"])
@login_required
def create_project():

    form = CreateNewProjectForm()

    user = User.query.get(current_user.id)
    organization = Organization.query.get(user.organization_id)

    if form.validate_on_submit():

        existing_project = Project.query.filter_by(name=form.name.data).first()

        if existing_project:
            flash("Project with that name already exists.", category="danger")
        else:
            new_project = Project(name=form.name.data, description=form.description.data)
            db.session.add(new_project)

            # Add current user to project team by default.
            new_project.team.append(current_user)
            # Add new_project to organization.projects
            organization.projects.append(new_project)

            db.session.commit()
            flash(f"{new_project.name} project created successfully", category="success")

        return redirect(url_for("views.my_projects"))

    if form.errors != {}:
        for err_msg in form.errors.values():
            flash(f"{err_msg}", category="danger")

    return render_template("create_project.html", form=form)


@views.route('/my-projects/<project_id>/create-ticket', methods=["GET", "POST"])
@login_required
def create_ticket(project_id):

    createNewTicketFormObject = init_CreateNewTicketForm()
    form = createNewTicketFormObject()

    user = User.query.get(current_user.id)
    organization = Organization.query.get(user.organization_id)

    if form.validate_on_submit():

        existing_ticket = Ticket.query.filter_by(name=form.name.data).first()

        if existing_ticket:
            flash("Ticket with that name already exists.", category="danger")
        else:
            project = Project.query.get(int(project_id))
            new_ticket = Ticket(name=form.name.data, description=form.description.data, priority=form.priority.data, type=form.type.data, status=form.status.data, assigned_dev=form.assigned_dev.data, project=project, created_by=flask_login.current_user.id)
            db.session.add(new_ticket)
            db.session.commit()
            flash("Ticket created successfully.", category="success")

            return redirect(url_for("views.project_details", project_id=project_id))

    if form.errors != {}:
        for err_msg in form.errors.values():
            flash(f"{err_msg}", category="danger")

    return render_template("create_ticket.html", form=form, organization=organization)


# Read routes
@views.route('/my-projects', methods=["GET", "POST"])
@login_required
def my_projects():

    projects = current_user.projects

    # When user selects delete project.
    if request.method == "POST":
        project_id = request.form["project_id"]
        project_to_delete = Project.query.get(int(project_id))
        if project_to_delete:
            db.session.delete(project_to_delete)
            # Delete all tickets within project_to_delete.
            for ticket in project_to_delete.tickets:
                db.session.delete(ticket)
            db.session.commit()
            flash(f"{project_to_delete.name} deleted successfully.", category="success")
            projects = current_user.projects

            return redirect(url_for("views.my_projects", projects=projects))

    return render_template("my_projects.html", projects=projects)


@views.route('/my-projects/<project_id>')
@login_required
def project_details(project_id):

    project = Project.query.get(int(project_id))

    return render_template("project_details.html", project=project)


@views.route('/my-tickets', methods=["GET", "POST"])
@login_required
def my_tickets():

    user = User.query.get(current_user.id)
    organization = Organization.query.get(user.organization_id)
    tickets = []

    for project in organization.projects:
        if user in project.team:
            for ticket in project.tickets:
                tickets.append(ticket)

    if request.method == "POST":
        ticket_id = request.form["ticket_id"]
        action = request.form["action"]
        ticket_to_edit = Ticket.query.get(int(ticket_id))
        if action == "edit":
            return redirect(url_for("views.edit_ticket", project_id=ticket_to_edit.project_id, ticket_id=ticket_id))
        elif action == "delete":
            db.session.delete(ticket_to_edit)
            db.session.commit()
            flash(f"{ticket_to_edit.name} {action}d successfully.", category="success")
            return redirect(url_for("views.my_tickets", organization=organization, tickets=tickets))
        elif action == "details":
            return redirect(url_for("views.ticket_details", project_id=ticket_to_edit.project.id, ticket_id=ticket_id))

    return render_template("my_tickets.html", organization=organization, tickets=tickets)


@views.route('/my-profile', methods=["GET", "POST"])
@login_required
def my_profile():

    form = EditProfileForm()

    if form.validate():
        first_name = form.first_name.data
        last_name = form.last_name.data
        email = form.email.data
        role = form.role.data
        current_password = form.password1.data
        new_password = form.password2.data

        if check_password_hash(current_user.password, current_password):
            user = User.query.get(current_user.id)
            user.first_name = first_name
            user.last_name = last_name
            user.email = email
            user.role = role
            user.password = generate_password_hash(new_password, method="sha256")

            db.session.commit()
            flash(f"Changes saved successfully", category="success")

            return redirect(url_for("views.my_profile"))
        else:
            flash("Incorrect password.", category="danger")

    return render_template("my_profile.html", form=form)


@views.route('/my-projects/<project_id>/ticket-details/<ticket_id>', methods=["GET", "POST"])
@login_required
def ticket_details(project_id, ticket_id):

    form = NewCommentForm()

    project = Project.query.get(int(project_id))
    ticket = Ticket.query.get(int(ticket_id))
    ticket_edits = TicketEdit.query.filter_by(ticket_id=ticket_id)

    # When submitting a comment.
    if form.validate_on_submit():
        new_comment = Comment(message=form.message.data, ticket=ticket, commenter=current_user.full_name)
        print(new_comment)
        db.session.add(new_comment)
        db.session.commit()
        flash("Comment submitted successfully.", category="success")

        return redirect(url_for('views.ticket_details', ticket_id=ticket_id, project_id=project_id))

    # When selecting ticket options.
    if request.method == "POST":
        ticket_id = request.form["ticket_id"]
        action = request.form["action"]
        ticket_to_edit = Ticket.query.get(int(ticket_id))
        if action == "edit":
            return redirect(url_for("views.edit_ticket", project_id=project_id, ticket_id=ticket_id))
        elif action == "delete":
            if ticket_to_edit:
                db.session.delete(ticket_to_edit)
                db.session.commit()
                flash(f"{ticket_to_edit.name} {action}d successfully.", category="success")

                return redirect(url_for("views.edit_project_tickets", project_id=project_id))

    return render_template("ticket_details.html", ticket=ticket, project=project, form=form, ticket_edits=ticket_edits)


# Update/Delete routes
@views.route('/my-projects/<project_id>/edit-project-tickets', methods=["GET", "POST"])
@login_required
def edit_project_tickets(project_id):

    project = Project.query.get(int(project_id))
    tickets = Ticket.query.filter_by(project=project)
    users = User.query.all()

    if request.method == "POST":
        ticket_id = request.form["ticket_id"]
        action = request.form["action"]
        ticket_to_edit = Ticket.query.get(int(ticket_id))
        if action == "edit":
            return redirect(url_for("views.edit_ticket", project_id=project_id, ticket_id=ticket_id))
        elif action == "delete":
            db.session.delete(ticket_to_edit)
            db.session.commit()
            flash(f"{ticket_to_edit.name} {action}d successfully.", category="success")
        elif action == "details":
            return redirect(url_for("views.ticket_details", project_id=project.id, ticket_id=ticket_id))

    return render_template("edit_project_tickets.html", project=project, tickets=tickets, users=users)


@views.route('/my-project/<project_id>/edit-project-tickets/<ticket_id>', methods=["GET", "POST"])
@login_required
def edit_ticket(project_id, ticket_id):

    EditTicketFormObject = init_CreateNewTicketForm()

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CDN -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

        <!-- Fontawesome CDN -->
        <script src="https://kit.fontawesome.com/bf6055dadc.js" crossorigin="anonymous"></script>

        <!-- Google fonts -->

        <!-- My CSS -->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/dashboard2.css') }}">

        <!-- JQuery CDN -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

        <!-- Chart.js CDN -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.8.0/chart.min.js" integrity="sha512-sW/w8s4RWTdFFSduOTGtk4isV1+190E/GghVffMA9XczdJ2MDzSzLEubKAs5h0wzgSJOQTRYyaz73L3d6RtJSg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

        <title>{% block title %}Base{% endblock %}</title>
    </head>

    <body>

        {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }} alert-dismissable fade show text-center" role="alert">
                      {{ message }}
                      <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        <div id="wrapper" class="sidebarShow">

            <!-- Top Nav -->
            <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
                    <a id="sidebar-toggle" class="btn btn-outline-secondary">
                        <i class="fa-solid fa-bars"></i>
                    </a>
                    <a class="navbar-brand" href="{{ url_for('views.dashboard') }}">Logged in as: {{ current_user.first_name }} {{ current_user.last_name }}</a>
                    <div id="navbar" class="collapse navbar-collapse float-end">
                        <div class="navbar-nav">
                        </div>
                    </div>
                </div>
            </nav>

            <!-- Sidebar Nav -->
            <div id="sidebar-wrapper">
                <ul class="sidebar-nav">
                    <li>
                        <a href="{{ url_for('views.dashboard') }}">
                            <i class="fa-solid fa-table"></i> Home
                        </a>
                    </li>
                    <li>
                        <a href="{{ url_for('views.my_projects') }}">
                            <i class="fa-solid fa-rectangle-list"></i> My Projects
                        </a>
                    </li>
                    <li>
                        <a href="{{ url_for('views.my_tickets') }}">
                            <i class="fa-solid fa-ticket"></i> My Tickets
                        </a>
                    </li>
                    <li>
                        <a href="{{ url_for('views.my_profile') }}">
                            <i class="fa-solid fa-user"></i> Profile
                        </a>
                    </li>
                    <li>
                        <a id="logout" href="{{ url_for('auth.logout') }}">
                            <i class="fa-solid fa-door-closed"></i> Logout
                        </a>
                    </li>
                </ul>
            </div>

            <!-- Dashboard Content -->
            <div id="dashboard-wrapper">
                {% block content %}
                {% endblock %}
            </div>
        </div>

        {% block scripts %}
        <!-- Sidebar toggle script -->
        <script>
            $("#sidebar-toggle").click( function (e) {
                e.preventDefault();
                $("#wrapper").toggleClass("sidebarShow");
            });
        </script>

        <!-- Bootstrap scripts -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

        {% endblock %} <!-- scripts -->
    </body>
</html>

website/templates/base2.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CDN -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

        <!-- Fontawesome CDN -->
        <script src="https://kit.fontawesome.com/bf6055dadc.js" crossorigin="anonymous"></script>

        <!-- Google fonts -->

        <!-- My CSS -->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/dashboard.css') }}">

        <title>{% block title %}Base{% endblock %}</title>
    </head>

    <body>

        {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }} alert-dismissable fade show text-center" role="alert">
                      {{ message }}
                      <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        <div id="wrapper">
            <!-- Top Nav -->
            <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{{ url_for('views.dashboard') }}">Logged in as: {{ current_user.first_name }} {{ current_user.last_name }}</a>
                    <div id="navbar" class="collapse navbar-collapse float-end">
                        <div class="navbar-nav">
                            {% if current_user.is_authenticated %}
                            <a id="logout" class="nav-item nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                            {% else %}
                            <a id="signup" class="nav-item nav-link" href="{{ url_for('auth.sign_up') }}">Sign-up</a>
                            <a id="login" class="nav-item nav-link" href="{{ url_for('auth.login') }}">Login</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>

            <!-- Main Dashboard -->
                <div class="row flex-nowrap">
                    <!-- Sidebar Nav -->
                    <div class="col-auto d-sm-inline bg-light d-sm-block sidebar shadow">
                        <div class="sidebar-left affix">
                            <ul class="nav flex-column align-items-sm-start">
                                <li class="nav-item align-middle w-100">
                                    <a class="nav-link" aria-current="page" href="{{ url_for('views.dashboard') }}">
                                        <i class="fa-solid fa-table"></i><span class="d-none d-sm-inline">Home</span>
                                    </a>
                                </li>
                                <li class="nav-item w-100">
                                    <a class="nav-link" href="{{ url_for('views.my_projects') }}">
                                        <i class="fa-solid fa-rectangle-list"></i><span class="d-none d-sm-inline">My Projects</span>
                                    </a>
                                </li>
                                <li class="nav-item w-100">
                                    <a class="nav-link" href="{{ url_for('views.my_tickets') }}">
                                        <i class="fa-solid fa-ticket"></i><span class="d-none d-sm-inline">My Tickets</span>
                                    </a>
                                </li>
                                <li class="nav-item w-100">
                                    <a class="nav-link" href="{{ url_for('views.my_profile') }}">
                                        <i class="fa-solid fa-user"></i><span class="d-none d-sm-inline">Profile</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- Dashboard Content -->
                    <div class="col-md-10 dashboard" style="display: block;">
                        {% block content %}
                        {% endblock %}
                    </div>
                </div>
        </div>

        <!-- Bootstrap scripts -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

       </script>
    </body>
</html>

website/templates/create_project.html
{% extends "base.html" %}

{% block title %}Create New Project{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title mb-2">Create New Project</h5>
                <h6 class="card-subtitle mb-4 text-muted">Enter new project details below and click "Create Project".</h6>
                <form method="POST" class="form-create-project">
                    {{ form.hidden_tag() }}
                    <div class="form-floating mb-3">
                        {{ form.name(class="form-control", id="floatingProjectName", placeholder="Project Name") }}
                        {{ form.name.label(for="floatingProjectName") }}
                    </div>
                    <div class="form-floating mb-3">
                        {{ form.description(class="form-control", id="floatingProjectDescription", placeholder="Project Description") }}
                        {{ form.description.label(for="floatingProjectDescription") }}
                    </div>
                    <div class="d-grid gap-2">
                        {{ form.submit(class="btn btn-primary") }}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

website/templates/edit_project_tickets.html
{% extends "base.html" %}

{% block title %}Edit Project Tickets{% endblock %}

{% block content %}
        <a style="margin-left: 12px;" class="btn btn-primary" href="{{ url_for('views.create_ticket', project_id=project.id) }}">Create new ticket</a>
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Edit Tickets for {{ project.name }}</h5>
            <a class="card-subtitle mb-2 text-muted" href="{{ url_for('views.project_details', project_id=project.id) }}">
                <i class="fa-solid fa-arrow-left"></i>Back to {{ project.name }} details
            </a>
            <!-- Search bar/functionality here. -->
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <th scope="col">Name</th>
                        <th scope="col">Description</th>
                        <th scope="col">Priority</th>
                        <th scope="col">Type</th>
                        <th scope="col">Status</th>
                        <th scope="col">Date Created</th>
                        <th scope="col">Actions</th>
                    </thead>
                    <tbody>
                    {% if tickets %}
                        {% for ticket in tickets %}
                        {% include "/includes/modals.html" %}
                            <tr>
                                <td class="align-middle">{{ ticket.name }}</td>
                                <td class="align-middle">{{ ticket.description }}</td>
                                <td class="align-middle">{{ ticket.priority }}</td>
                                <td class="align-middle">{{ ticket.type }}</td>
                                <td class="align-middle">{{ ticket.status }}</td>
                                <td class="align-middle">{{ ticket.date_created }}</td>
                                <td>
                                    <form method="POST">
                                        <input type="hidden" name="ticket_id" value="{{ ticket.id }}">
                                        <button name="action" value="details" class="btn btn-info mb-1">More Details</button>
                                        <button name="action" value="edit" class="btn btn-primary mb-1">Edit Ticket</button>
                                        <button type="button" class="btn btn-danger mb-1" data-bs-toggle="modal"
                                                data-bs-target="#ConfirmTicketDeleteModal-{{ ticket.id }}">
                                            Delete Ticket
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                    {% endif %}
                    </tbody>
                </table>
            </div>
          </div>
        </div>
{% endblock %}

website/templates/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CDN -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

        <!-- Fontawesome CDN -->
        <script src="https://kit.fontawesome.com/bf6055dadc.js" crossorigin="anonymous"></script>

        <!-- Google fonts -->

        <!-- My CSS -->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">

        <title>{% block title %}Login{% endblock %}</title>
    </head>

    <body>

    {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }} alert-dismissable fade show text-center" role="alert">
                  {{ message }}
                  <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

        <div id="wrapper">

            <!-- Main div -->
            <div id="main">
                {% block content %}
                <div class="container-fluid log-in">
                    <div class="d-flex justify-content-center">
                        <div class="card" style="width: 30rem">
                            <div class="card-header text-center">
                                <h3><i class="fa-solid fa-bug"></i>  Log-In</h3>
                            </div>
                            <div class="card-body mt-3 ms-5 me-5 mb-3">
                                <form method="POST" class="form-sign-up">
                                    {{ form.hidden_tag() }}
                                    <div class="form-floating mb-3">
                                        {{ form.email(class="form-control", id="floatingEmail", placeholder="Email") }}
                                        {{ form.email.label(for="floatingEmail") }}
                                    </div>
                                    <div class="form-floating mb-3">
                                        {{ form.password(class="form-control", id="floatingPassword", placeholder="Password") }}
                                        {{ form.password.label(for="floatingPassword") }}
                                    </div>
                                    <div>
                                        <span><input type="checkbox"> Remember Me</span>
                                    </div>
                                    <br>
                                    <div class="d-grid gap-2">
                                      {{ form.submit(class="btn btn-primary") }}
                                    </div>
                                </form>
                            </div>
                            <div class="card-footer">
                                <div class="d-flex justify-content-center">
                                    <span>Forgot your <a href="#">Password</a>?</span>
                                </div>
                                <div class="d-flex justify-content-center">
                                    <span>New User? <a href="{{ url_for('auth.sign_up', demo_login=False) }}">Sign-Up</a>!</span>
                                </div>
                                <div class="d-flex justify-content-center">
                                    <span>Sign-in as a <a href="{{ url_for('auth.demo') }}">Demo User</a>.</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                    <!-- Pixel Art -->
<!--                <div class="container-fluid">-->
<!--                    <div class="pokeball">-->
<!--                        <div class="pixel"></div>-->
<!--                    </div>-->
<!--                </div>-->

                {% endblock %}
            </div> <!-- Main div -->

            <footer>
                <p></p>
            </footer>

        </div> <!-- Wrapper -->


        <!-- Bootstrap scripts -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    </body>
</html>